build: false
version: "{branch}-{build}"

image:
  - Visual Studio 2013
  - Visual Studio 2015
  - Visual Studio 2017

environment:
  GNOME_BASE: https://ftp.gnome.org/pub/gnome/binaries/win32
  LIBOGG: libogg-1.3.3
  LIBOGG_VS: VS2015
  LIBOGG_CONFIG: Release
  LIBOGG_PLAT: Win32
  LIBRARY_PATH: C:\projects\bfg9000\lib
  PYTHON_PATH: C:\Python27
  BFG_SKIPPED_TESTS: scala
  BACKENDS: ninja make msbuild
  CPPFLAGS: /IC:\projects\bfg9000\include /WX

  matrix:
    - COMPILER: vs
    - COMPILER: mingw
    - COMPILER: cygwin

matrix:
  exclude:
    - image: Visual Studio 2013
      COMPILER: mingw
    - image: Visual Studio 2013
      COMPILER: cygwin
    - image: Visual Studio 2015
      COMPILER: mingw
    - image: Visual Studio 2015
      COMPILER: cygwin

for:
  - matrix:
      only:
        - image: Visual Studio 2013
    environment:
      VS: C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat
      BOOST_INCLUDEDIR: C:\Libraries\boost_1_58_0
      BOOST_LIBRARYDIR: C:\Libraries\boost_1_58_0\lib32-msvc-12.0
      LIBOGG: libogg-1.3.2
      LIBOGG_VS: VS2010
      CHOCO_EXTRAS: make
  - matrix:
      only:
        - image: Visual Studio 2015
    environment:
      VS: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat
      BOOST_INCLUDEDIR: C:\Libraries\boost_1_63_0
      BOOST_LIBRARYDIR: C:\Libraries\boost_1_63_0\lib32-msvc-14.0
      CHOCO_EXTRAS: make
  - matrix:
      only:
        - image: Visual Studio 2017
          COMPILER: vs
    environment:
      VS: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat
      BOOST_INCLUDEDIR: C:\Libraries\boost_1_67_0
      BOOST_LIBRARYDIR: C:\Libraries\boost_1_67_0\lib32-msvc-14.1
      CHOCO_EXTRAS: make
  - matrix:
      only:
        - image: Visual Studio 2017
          COMPILER: mingw
    environment:
      BACKENDS: ninja make
      CC: gcc
      CXX: g++
      CPPFLAGS: -IC:\projects\bfg9000\include -Wall -Werror
      MAKE: mingw32-make
      MINGW_PATH: C:\msys64\mingw64\bin
      LIBOGG_PLAT: x64
  - matrix:
      only:
        - image: Visual Studio 2017
          COMPILER: cygwin
    environment:
      BACKENDS: ninja make
      CPPFLAGS: -Wall -Werror
    install:
      - >
        C:\cygwin64\setup-x86_64 -qnNd -l C:\cygwin64\var\cache\setup
        -R c:\cygwin64 -P python27 -P python27-pip -P python27-setuptools
        -P ninja
    build_script:
      - xcopy /i /q /s /h C:\projects\bfg9000 C:\cygwin64\home\appveyor\bfg9000
      - C:\cygwin64\bin\bash -lc "cd bfg9000 && pip2 install codecov coverage mock ."
    test_script:
      - C:\cygwin64\bin\bash -lc "cd bfg9000 && python setup.py coverage -s test.integration.test_executable"
    on_success:
      - C:\cygwin64\bin\bash -lc "cd bfg9000 && codecov"

cache:
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml

install:
  - cinst gnuwin32-coreutils.portable ninja %CHOCO_EXTRAS%

  # Fetch and install pkg-config.
  - curl -LO %GNOME_BASE%/dependencies/pkg-config_0.26-1_win32.zip
  - curl -LO %GNOME_BASE%/glib/2.28/glib_2.28.8-1_win32.zip
  - curl -LO %GNOME_BASE%/dependencies/gettext-runtime_0.18.1.1-2_win32.zip
  - 7z x -y pkg-config_0.26-1_win32.zip -oC:\pkg-config > nul
  - 7z x -y glib_2.28.8-1_win32.zip -oC:\pkg-config > nul
  - 7z x -y gettext-runtime_0.18.1.1-2_win32.zip -oC:\pkg-config > nul
  - set PKG_CONFIG=C:\pkg-config\bin\pkg-config.exe

  # Build and install libogg.
  - curl -LO http://downloads.xiph.org/releases/ogg/%LIBOGG%.zip
  - 7z x -y %LIBOGG%.zip > nul
  - >
    msbuild %LIBOGG%\win32\%LIBOGG_VS%\libogg_dynamic.sln
    /p:Configuration=%LIBOGG_CONFIG% /p:Platform=%LIBOGG_PLAT%
  - mkdir lib
  - set LIBOGG_BUILDDIR=%LIBOGG%\win32\%LIBOGG_VS%\%LIBOGG_PLAT%\%LIBOGG_CONFIG%
  - copy %LIBOGG_BUILDDIR%\libogg.lib lib\ogg.lib
  - copy %LIBOGG_BUILDDIR%\libogg.dll lib\libogg.dll
  - robocopy %LIBOGG%\include include *.h /E & exit 0

  # Set up paths and other necessary bits for the compiler.
  - if defined VS call "%VS%" x86
  - set PATH=%MINGW_PATH%;%LIBRARY_PATH%;%PATH%
  - set PATH=%PYTHON_PATH%;%PYTHON_PATH%\Scripts;%PATH%

  # Make a `libogg.a` file for MinGW.
  - >
    if defined MINGW_PATH gendef lib\libogg.dll &
    dlltool -U -d libogg.def -l lib\libogg.a & del libogg.def
build_script:
  - pip install codecov lxml==3.6.0 .[test]
test_script:
  - python setup.py coverage -q
on_success:
  - codecov
